version: 0.0
os: linux
files:
  - source: #hay que ir a donde está el .war
    destination: /opt/tomcat/webapps
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationBeforeInstall:
    - location: codedeploy-scripts/beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
