name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
      
    - name: Gradlew Permissions
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    
    - name: SHA Value
      run: echo "SHA=${{github.sha}}">>$GITHUB_ENV

    - name: Para ver si imprime bien el hash en la consola
      run: echo $SHA

      # Ahora faltaría crear el cloudformation y el codedeploy